sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in svc-account.json.enc -out svc-account.json -d
  # DL gcsdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #  Default install dir, source file (get the config to modify shell)
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install/update kubectl in travis environment
  - gcloud components update kubectl
  # Authenticate (like IAM on aws)
  # Sensitive creds, never in source control
  - gcloud auth activate-service-account --key-file service-account.json
