# Not an instance of storage
# Claims are 'advertisements' of potential
# volumes

apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: database-persistent-volume-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
